[package]

name = "qpickwrapper"
version = "0.0.1"
authors = ["Dragan Cvetinovic <dcvetinovic@gmail.com>"]

[lib]
name = "qpickwrapper"
crate-type = ["dylib"]

[dependencies]
libc = "0.2"
qpick = { path = "/ebs/qpick/", version = "0.1.0" }
